# Generated by Django 3.2.4 on 2021-06-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.IntegerField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
