# Generated by Django 3.2.4 on 2021-06-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
    ]
